// Generated by CoffeeScript 1.10.0
exports.Renderer = require('./Renderer');

exports.render = function(data, imagePath, opts, cb) {
  var r;
  r = new exports.Renderer(data, imagePath, opts);
  return r.render(cb);
};
